
services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db

  backend:
    container_name: backend
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    links:
      - db:database
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend
    ports:
      - 3000:3000

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db

  stats:
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats

  user-ops-indexer:
    depends_on:
      - db
      - backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer
    extra_hosts:
      - "host.docker.internal:host-gateway"

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/nginx.yml
      service: proxy

  # seismic-reth:
  #   image: seismic-reth
  #   ports:
  #     - "8551"             # Auth RPC
  #     - "8545:8545"       # HTTP RPC
  #     - "30303"            # Execution P2P
  #     - "30303:30303/udp"  # Execution P2P Discovery
  #     - "8546"             # Websockets RPC
  #     - "6060"             # Prometheus metrics and pprof
    
  geth:
    image: "ethereum/client-go:v1.14.11"
    command:
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=engine,eth,net,web3
      - --http.vhosts="host.docker.internal,localhost,*"
      - --http.corsdomain="*"
    ports:
      - "8551"             # Auth RPC
      - "8545:8545"       # HTTP RPC
      - "30303"            # Execution P2P
      - "30303:30303/udp"  # Execution P2P Discovery
      - "8546"             # Websockets RPC
      - "6060"             # Prometheus metrics and pprof
    extra_hosts:
      - "host.docker.internal:host-gateway"